depman:
  build: .
  volumes:
   - ./rpmfiles:/tmp/depman_data
  ports:
   - "8082:8082"
  links:
   - postgres

postgres:
  build: ./postgres
  volumes:
   - /tmp/pgdata:/var/lib/postgresql/data
  environment:
    POSTGRES_PASSWORD: postgres
    PGDATA: /var/lib/postgresql/data/pgdata
  ports:
   - "5432:5432"
